### ISSUE TITLE
How do I call object to extract grid data into numpy array?

### ISSUE THREAD

**Issue by hal98x** [3ptscience/steno3d-surfer#3]
I am interested in manipulating the grid files outside of steno3D. How do I extract the griddata to a numpy array?

Maybe what would be more useful though is could you extend steno3d-surfer to export a python dictionary of the header information and data (bounds, grid spacing, x y vectors gridded data etc)?

**Comment by fwkoch** [comment]
I added an extract function that creates a python dictionary rather than a Steno3D project from the grd file. Take a look [here](https://github.com/3ptscience/steno3d-surfer/blob/v0.0.3/steno3d_surfer/parser.py#L81) and see if that is what you are looking for.

**Comment by hal98x** [comment]
Works good. Could you write a function to do the reverse (dict -> parser object)? 
This way I could extract fix the grid or run some math on it and then toss it back too steno3d.

Sincerely,

Michael Wallace

**Comment by fwkoch** [comment]
Take a look at #6 now. Instead of extracting a dictionary, it extracts a `GridInfo` object. This is type-checked and validated. It may be modified, then has a `to_steno3d` which creates the Steno3D Project. Let me know what you think!

**Comment by hal98x** [comment]
The GridInfo class is not underneath the right base class. it needs to be under grd instead of parser
I import with this command
parser = steno3d.parsers.grd('data/EMPda_9000_clip.grd')

then if I go parser. there is no GridInfo

if I do steno3d_surfer.parser.  then GridInfo appears as a class. 

Thanks for forcing me to get familiar with github haven't done this in awhile. 

Michael

**Comment by fwkoch** [comment]
Hi @hal98x - Thanks for checking this out (and working with me on github)!

To get the `GridInfo` instance, you need to call `extract` on the parser (ie `parser.parse()` returns `steno3d.Project`, `parser.extract()` returns `GridInfo`). You probably will not need to access the `GridInfo` class directly, just the `extract` method, but I think if you do `steno3d_surfer.parser.GridInfo` is the appropriate location (rather than the `steno3d.parsers` namespace which should only contain parsers, not helper classes).

Here's a screenshot of my workflow using this. Let me know if you have any followup questions.

<img width="1023" alt="screen shot 2017-04-12 at 8 42 49 am" src="https://cloud.githubusercontent.com/assets/9453731/24963743/b1eea136-1f5c-11e7-8d1f-eca25fd50ef3.png">

**Comment by hal98x** [comment]
Ok thank you for the clarification on how to get too grd_info. This works really well and will be very helpful. Also learned a little about github and patching python code.

**Comment by fwkoch** [comment]
Wonderful. I'm glad this is helpful. I'm going to close this issue, but you are welcome to reopen if something else comes up.
